### ISSUE TITLE
GitHub Username 

### ISSUE THREAD

**Issue by apeltzer** [systemfabrikken/gradle-githubrelease-plugin#2]
Hi!

`   githubAuthUsername = githubUsername ?: "$System.env.GITHUB_USER"
    githubAuthToken = githubToken ?: "$System.env.GITHUB_TOKEN"`

should be:

`    githubAuthUsername = hasProperty('GITHUB_USER') ?: '$SYSTEM.ENV.GITHUB_USER'
    githubAuthToken = hasProperty('GITHUB_TOKEN') ?: '$SYSTEM.ENV.GITHUB_TOKEN'`

otherwise, it doesnt work for me when setting my stuff in ~/.gradle/gradle.properties like this:

GITHUB_USER=apeltzer
GITHUB_TOKEN=XYZZXZYZYZY

**Comment by kaililleby** [comment]
Hi, 
I wrote it like `githubAuthUsername = githubUsername ?: "$System.env.GITHUB_USER"` so that the property can be set either through  ~/.gradle/gradle.properties using githubUsername=... or by specifying GITHUB_USER in the shell env. 

Replacing GITHUB_USER=apeltzer with githubUsername=apeltzer in you  ~/.gradle/gradle.properties should make it work..

Also note that the expression `githubAuthUsername = hasProperty('GITHUB_USER') ?: '$SYSTEM.ENV.GITHUB_USER'` would set githubAuthUsername to the boolean value `true` if GITHUB_USER is set, probably not what you intended :)
